name: Package Distribution

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Package Distribution
      uses: gradle/gradle-build-action@v2
      with:
        arguments: packageDistributionForCurrentOS

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables-${{ matrix.os }}
        path: build/compose/binaries/main/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/compose/binaries/main/**/*
        draft: false
        prerelease: false
        
    
