name: Package Distribution

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    # Run on PRs from develop or when a PR is merged to master
    if: |
      (github.event_name == 'pull_request' && github.head_ref == 'develop') ||
      (github.event_name == 'push' && github.event.pull_request.merged == true)
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Package Distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageDistributionForCurrentOS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executables-${{ matrix.os }}
          path: build/compose/binaries/main/

      - name: Generate Release Tag
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        id: tag
        run: |
          VERSION=$(date +'v%Y.%m.%d-%H%M')
          echo "new_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/compose/binaries/main/**/*
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false

permissions:
  contents: write
